lsi: false
safe: true
name: Björn Strausmann
theme: kramdown
url: "https://strausmann.github.io"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge